<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-1G99RHJC" failures="1" tests="1" name="Default test" time="29.446" errors="0" timestamp="2022-06-09T11:49:28 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.649">
    <failure type="java.lang.AssertionError" message="expected [Failure message] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [Failure message] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at nopCommerce.StepDefination.EditLead.verifyCompanyName(EditLead.java:102)
at âœ½.Confirm the changed name appears(file:///D:/practice/nopCommerce/src/test/java/nopCommerce/Feature/EditLead.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
