<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-1G99RHJC" failures="1" tests="1" name="nopCommerce.TestRunner.TestRunner" time="28.943" errors="0" timestamp="2022-06-09T11:49:28 IST" skipped="0">
  <testcase classname="nopCommerce.TestRunner.TestRunner" name="runScenario" time="28.943">
    <failure message="expected [Failure message] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Failure message] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at nopCommerce.StepDefination.EditLead.verifyCompanyName(EditLead.java:102)
at âœ½.Confirm the changed name appears(file:///D:/practice/nopCommerce/src/test/java/nopCommerce/Feature/EditLead.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- nopCommerce.TestRunner.TestRunner -->
